name: Run Python Unit Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Run unit tests
              run: |
                  # If you use unittest and your tests are test*.py
                  python -m unittest discover -s . -p "test*.py"
